cargo-features = ["edition"]

[package]
name = "heartache"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
edition = '2018'

[dependencies]
ggbasm = { path = "/home/rubic/Projects/Crates/ggbasm/ggbasm" }
failure = "0.1"
