#!/usr/bin/env python3

text_out = "; This file is generated by 'generate.py' do not edit\n"
section_count = {}

ascii_to_byte = {
    # alphabet
    'a': 0,
    'b': 1,
    'c': 2,
    'd': 3,
    'e': 4,
    'f': 5,
    'g': 6,
    'h': 7,
    'i': 8,
    'j': 9,
    'k': 10,
    'l': 11,
    'm': 12,
    'n': 13,
    'o': 14,
    'p': 15,
    'q': 16,
    'r': 17,
    's': 18,
    't': 19,
    'u': 20,
    'v': 21,
    'w': 22,
    'x': 23,
    'y': 24,
    'z': 25,
    '!': 26,
    '?': 27,
    '.': 28,
    ',': 29,
    "'": 30,
    ' ': 31,
    # control characters
   '\n': 255, # end string
    '|': 254, # next line
    '>': 253, # large wobble
    '<': 252, # small wobble
    '^': 251, # slow down
}

with open('strings.txt', 'r') as file_in:
    for line in file_in.readlines():
        section, text = line.split('$')
    
        count = section_count.get(section, 0);
        text_out += "\nText{}{}:\n".format(section, count)

        for char in text:
            char = char.lower() # DELETE WHEN IMPLEMENT UPPER CASE
            text_out += "   db ${:02x}\n".format(ascii_to_byte[char])

        section_count[section] = section_count.get(section, 0) + 1

with open('strings.asm', 'wb') as out:
    out.write(bytes(text_out, "ascii"))
