#!/usr/bin/env python3

text_out = "; This file is generated by 'generate.py' do not edit\n"
section_count = {}

with open('text.txt', 'r') as file_in:
    for line in file_in.readlines():
        section, text = line.split('$')
    
        count = section_count.get(section, 0);
        text_out += "\nText{}{}:\n".format(section, count)

        for char in text:
            text_out += "   db ${:02x}\n".format(ord(char))

        section_count[section] = section_count.get(section, 0) + 1

with open('text.asm', 'wb') as out:
    out.write(bytes(text_out, "ascii"))
